server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: knowledge-hub-backend
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/knowledge_hub
      auto-index-creation: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: knowledgeHubSecretKey2024!@#$%^&*()
  expiration: 86400000 # 24 hours in milliseconds

# File Storage Configuration
file:
  upload-dir: ./uploads
  allowed-types: pdf,doc,docx,jpg,jpeg,png

# Logging
logging:
  level:
    com.knowledgehub: DEBUG
    org.springframework.security: DEBUG
